ServerName localhost

<VirtualHost *:80>
    ProxyPreserveHost On
    ProxyPass / http://api:5000/
    ProxyPassReverse / http://api:5000/
</VirtualHost>

# Load MPM module
LoadModule mpm_worker_module modules/mod_mpm_worker.so

# Essential proxy modules
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so

ErrorLog /usr/local/apache2/logs/error.log
CustomLog /usr/local/apache2/logs/access.log common

